---
- hosts: localhost
  connection: local
  vars:
    username: sebastian
    group: sebastian
    dpdhl_ca_i5_cert: "DPDHL Global TLS CA - I5"

  tasks:
    #  - include: tasks/packages_yay.yaml
    - include_tasks: tasks/packages_snap.yaml
    - include_tasks: tasks/packages_flatpak.yaml
    - include_tasks: tasks/syncthing.yaml
    - include_tasks: tasks/client1-vpn.yaml
    - include_tasks: tasks/zsh.yaml
    - include_tasks: tasks/misc.yaml
    - include_tasks: tasks/sdkman.yaml
    - include_tasks: tasks/docker.yaml
    - include_tasks: tasks/certs.yaml
    - include_tasks: tasks/fonts.yaml
    - include_tasks: tasks/theming-kde.yaml
