#!/bin/sh

alias l='ls -la --color --group-directories-first'
alias ..='cd ..'
alias b='bat'
alias srz='source ~/.config/zsh/.zshrc'
alias idea='intellij-idea-ultimate-edition'
alias k='kubectl'
alias mk='minikube'
alias mkreset='~/workspace/personal/workstation/files/scripts/minikube-reset.sh'

# git
alias gpr='git pull -r'
alias gst='git status'
