#!/bin/sh

alias l='ls -la --color --group-directories-first'
alias ..='cd ..'
alias b='bat'
alias c='cat'
alias cat='bat -p'
alias srz='source ~/.config/zsh/.zshrc'
alias idea='intellij-idea-ultimate-edition'
alias mk='minikube'
alias mkreset='~/workspace/personal/workstation/files/scripts/minikube-reset.sh'
alias n='nvim'

# git
alias gpr='git pull -r'
alias gst='git status'

#kubectl
alias ki='kubectl cluster-info'
alias k='kubectl'
alias kpods='kubectl get pods -A'
alias kns='kubectl config view --minify | grep namespace:'
alias ksetns=''
alias klogs='kubectl logs'
alias kcon='kubectl config get-contexts'
alias kinfo='kubectl cluster-info'
